services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - "${RABBITMQ_MESSAGING_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - aqtf_shared_network
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rmq_cloud_data:/var/lib/rabbitmq

  mqtt:
    image: eclipse-mosquitto:2
    container_name: ${MQTT_CONTAINER_NAME}
    ports:
      - "${CLOUD_MQTT_PORT}:1883"
    networks:
      - aqtf_shared_network
    restart: always
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

networks:
  aqtf_shared_network:
    external: true

volumes:
  rmq_cloud_data:
  mosquitto_data:
  mosquitto_log:
