version: "3.8"
services:
  cloud_app:
    image: cloud_node_app:latest
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mqtt
    environment:
      - RABBITMQ_HOST=${RABBITMQ_CONTAINER_NAME}
      - CLOUD_RABBITMQ_HOST=${CLOUD_RABBITMQ_HOST}
      - CLOUD_MQTT_HOST=${CLOUD_MQTT_HOST}
      - CLOUD_MQTT_PORT=${CLOUD_MQTT_PORT}
    ports:
      - "${APP_HOST_PORT}:8081"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - aqtf_shared_network
    command: uvicorn cloud.communication.app_factory:app --host 0.0.0.0 --port 8081
    volumes:
      - ./models:/app/models

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - "${RABBITMQ_MESSAGING_PORT}:5672"    # Messaging port
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"  # Management UI
    networks:
      - aqtf_shared_network

  mqtt:
    image: eclipse-mosquitto
    container_name: ${MQTT_CONTAINER_NAME}
    ports:
      - "${CLOUD_MQTT_PORT}:1883"
    networks:
      - aqtf_shared_network
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

networks:
  aqtf_shared_network:
    external: true