services:
  cloud_app:
    image: cloud_node_app:latest
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - mqtt
    environment:
      - RABBITMQ_HOST=${RABBITMQ_CONTAINER_NAME}
      - CLOUD_RABBITMQ_HOST=${CLOUD_RABBITMQ_HOST}
      - CLOUD_MQTT_HOST=${CLOUD_MQTT_HOST}
      - CLOUD_MQTT_PORT=${CLOUD_MQTT_PORT}
      - APP_HOST_PORT=${APP_HOST_PORT}
    ports:
      - "${APP_HOST_PORT}:8081"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - aqtf_shared_network
    command: uvicorn cloud.communication.app_factory:app --host 0.0.0.0 --port 8081
    volumes:
      - ./models:/app/models
      - ./status:/app/status
      - /sys/class/net:/host_sys/class/net:ro

networks:
  aqtf_shared_network:
    external: true