services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - "${RABBITMQ_MESSAGING_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - aqtf_shared_network
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rmq_fog_data:/var/lib/rabbitmq
    extra_hosts:
      - "cloud:192.168.2.220"
      - "rabbitmq-cloud:192.168.2.220"
      - "mqtt-cloud:192.168.2.220"

  mqtt:
    image: eclipse-mosquitto:2
    container_name: ${MQTT_CONTAINER_NAME}
    ports:
      - "${FOG_MQTT_HOST_PORT}:1883"
    networks:
      - aqtf_shared_network
    restart: always
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    extra_hosts:
      - "cloud:${CLOUD_IP}"
      - "rabbitmq-cloud:${CLOUD_IP}"
      - "mqtt-cloud:${CLOUD_IP}"

networks:
  aqtf_shared_network:
    external: true

volumes:
  rmq_fog_data:
  mosquitto_data:
  mosquitto_log:
