services:
  fog_app:
    image: fog_node_app:latest
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=${RABBITMQ_CONTAINER_NAME}
      - FOG_HOST=${FOG_HOST}
      - CLOUD_HOST=${CLOUD_HOST}
      - FOG_RABBITMQ_HOST=${RABBITMQ_HOST}
      - CLOUD_RABBITMQ_HOST=${CLOUD_RABBITMQ_HOST}
      - FOG_MQTT_HOST=${FOG_MQTT_HOST}
      - FOG_MQTT_PORT=${FOG_MQTT_PORT}
      - HOST_IFACE=enp3s0
      - APP_HOST_PORT=${APP_HOST_PORT}
    ports:
      - "${APP_HOST_PORT}:8081"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - aqtf_shared_network
    command: uvicorn fog.communication.app_factory:app --host 0.0.0.0 --port 8081
    volumes:
      - ./models:/app/models
      - ./models/outbox:/app/models/outbox
      - /sys:/host_sys:ro
    extra_hosts:
      - "cloud:${CLOUD_IP}"
      - "rabbitmq-cloud:${CLOUD_IP}"
      - "mqtt-cloud:${CLOUD_IP}"

networks:
  aqtf_shared_network: {} # {} used for remote nodes
    # use only when all nodes on same host
    # external: true