version: "2.4"
services:
  edge_app:
    image: edge_node_app:latest
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FOG_RABBITMQ_HOST=${FOG_RABBITMQ_HOST}
      - FOG_MQTT_HOST=${FOG_MQTT_HOST}
      - FOG_MQTT_PORT=${FOG_MQTT_PORT}
      - TF_CPP_MIN_LOG_LEVEL=2
      - TF_ENABLE_ONEDNN_OPTS=0
    ports:
      - "${APP_HOST_PORT}:8081"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - aqtf_shared_network
    command: uvicorn edge.communication.app_factory:app --host 0.0.0.0 --port 8081
    mem_limit: 3g
    volumes:
      - ./models:/app/models
      - /sys/class/net:/host_sys/class/net:ro

networks:
  aqtf_shared_network:
    external: true